name: Deploy

on:
  schedule:
    - cron: '0 4 * * 0' # At 04:00 on Sunday
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  push_to_registry:
    name: Push (${{ matrix.cfg.base }}-${{ matrix.cfg.tag_name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        cfg:
          # Alma Linux
          - { base: "almalinux", tag: "9", tag_name: "9", extra_args: "" }
          - { base: "almalinux", tag: "8", tag_name: "8", extra_args: "" }

          # Amazon Linux
          - { base: "amazonlinux", tag: "2",       tag_name: "2",       extra_args: "" }
          - { base: "amazonlinux", tag: "1",       tag_name: "1",       extra_args: "" }
          - { base: "amazonlinux", tag: "2023",    tag_name: "2023",    extra_args: "" }
          - { base: "amazonlinux", tag: "2022",    tag_name: "2022",    extra_args: "" }
          - { base: "amazonlinux", tag: "2018.03", tag_name: "2018.03", extra_args: "" }
          - { base: "amazonlinux", tag: "2017.12", tag_name: "2017.12", extra_args: "" }
          - { base: "amazonlinux", tag: "2017.09", tag_name: "2017.09", extra_args: "" }
          - { base: "amazonlinux", tag: "2017.03", tag_name: "2017.03", extra_args: "" }
          - { base: "amazonlinux", tag: "2016.09", tag_name: "2016.09", extra_args: "" }

          # Debian
          - { base: "debian", tag: "testing-slim",  tag_name: "testing",  extra_args: "" }
          - { base: "debian", tag: "unstable-slim", tag_name: "unstable", extra_args: "" }
          - { base: "debian", tag: "12-slim",       tag_name: "12",       extra_args: "" }
          - { base: "debian", tag: "11-slim",       tag_name: "11",       extra_args: "" }
          - { base: "debian", tag: "10-slim",       tag_name: "10",       extra_args: "" }
          - { base: "debian", tag: "9-slim",        tag_name: "9",        extra_args: "OLD_RELEASE=true" }

          # Elementary OS
          - { base: "elementaryos", tag: "horus-stable",           tag_name: "horus-stable",           extra_args: "" }
          - { base: "elementaryos", tag: "horus-unstable",         tag_name: "horus-unstable",         extra_args: "" }
          - { base: "elementaryos", tag: "juno-stable",            tag_name: "juno-stable",            extra_args: "" }
          - { base: "elementaryos", tag: "juno-unstable",          tag_name: "juno-unstable",          extra_args: "" }
          - { base: "elementaryos", tag: "loki-stable",            tag_name: "loki-stable",            extra_args: "" }
          - { base: "elementaryos", tag: "loki-unstable",          tag_name: "loki-unstable",          extra_args: "" }
          - { base: "elementaryos", tag: "odin-stable",            tag_name: "odin-stable",            extra_args: "" }
          - { base: "elementaryos", tag: "odin-unstable",          tag_name: "odin-unstable",          extra_args: "" }
          - { base: "elementaryos", tag: "ubuntu-lunar-unstable",  tag_name: "ubuntu-lunar-unstable",  extra_args: "" }
          - { base: "elementaryos", tag: "ubuntu-mantic-unstable", tag_name: "ubuntu-mantic-unstable", extra_args: "" }
          - { base: "elementaryos", tag: "ubuntu-noble-unstable",  tag_name: "ubuntu-noble-unstable",  extra_args: "" }

          # Fedora
          - { base: "fedora", tag: "41", tag_name: "41", extra_args: "" }
          - { base: "fedora", tag: "40", tag_name: "40", extra_args: "" }
          - { base: "fedora", tag: "39", tag_name: "39", extra_args: "" }
          - { base: "fedora", tag: "38", tag_name: "38", extra_args: "" }
          - { base: "fedora", tag: "37", tag_name: "37", extra_args: "" }
          - { base: "fedora", tag: "36", tag_name: "36", extra_args: "" }
          - { base: "fedora", tag: "35", tag_name: "35", extra_args: "" }
          - { base: "fedora", tag: "34", tag_name: "34", extra_args: "" }
          - { base: "fedora", tag: "33", tag_name: "33", extra_args: "" }
          - { base: "fedora", tag: "32", tag_name: "32", extra_args: "" }
          - { base: "fedora", tag: "31", tag_name: "31", extra_args: "" }
          - { base: "fedora", tag: "30", tag_name: "30", extra_args: "" }
          - { base: "fedora", tag: "29", tag_name: "29", extra_args: "" }
          - { base: "fedora", tag: "28", tag_name: "28", extra_args: "" }
          - { base: "fedora", tag: "27", tag_name: "27", extra_args: "" }
          - { base: "fedora", tag: "26", tag_name: "26", extra_args: "" }
          - { base: "fedora", tag: "25", tag_name: "25", extra_args: "" }
          - { base: "fedora", tag: "24", tag_name: "24", extra_args: "" }
          - { base: "fedora", tag: "23", tag_name: "23", extra_args: "" }
          - { base: "fedora", tag: "22", tag_name: "22", extra_args: "" }
          - { base: "fedora", tag: "21", tag_name: "21", extra_args: "" }

          # Kali Linux
          - { base: "kalilinux", tag: "kali-rolling",      tag_name: "rolling",      extra_args: "" }
          - { base: "kalilinux", tag: "kali-last-release", tag_name: "last-release", extra_args: "" }

          # Linux Mint
          - { base: "linuxmint", tag: "22",   tag_name: "22",   extra_args: "" }
          - { base: "linuxmint", tag: "21.3", tag_name: "21.3", extra_args: "" }
          - { base: "linuxmint", tag: "21.2", tag_name: "21.2", extra_args: "" }
          - { base: "linuxmint", tag: "21.1", tag_name: "21.1", extra_args: "" }
          - { base: "linuxmint", tag: "21",   tag_name: "21",   extra_args: "" }
          - { base: "linuxmint", tag: "20.3", tag_name: "20.3", extra_args: "" }
          - { base: "linuxmint", tag: "20.2", tag_name: "20.2", extra_args: "" }
          - { base: "linuxmint", tag: "20.1", tag_name: "20.1", extra_args: "" }
          - { base: "linuxmint", tag: "20",   tag_name: "20",   extra_args: "" }
          - { base: "linuxmint", tag: "19.3", tag_name: "19.3", extra_args: "" }
          - { base: "linuxmint", tag: "19.2", tag_name: "19.2", extra_args: "" }
          - { base: "linuxmint", tag: "19.1", tag_name: "19.1", extra_args: "" }
          - { base: "linuxmint", tag: "19",   tag_name: "19",   extra_args: "" }
          - { base: "linuxmint", tag: "18",   tag_name: "18",   extra_args: "" }
          - { base: "linuxmint", tag: "17",   tag_name: "17",   extra_args: "" }

          # Linux Mint Debian Edition
          - { base: "lmde", tag: "6", tag_name: "6", extra_args: "" }
          - { base: "lmde", tag: "5", tag_name: "5", extra_args: "" }
          - { base: "lmde", tag: "4", tag_name: "4", extra_args: "" }

          # Manjaro
          - { base: "manjaro", tag: "latest", tag_name: "latest", extra_args: "" }

          # Oracle Linux
          - { base: "oraclelinux", tag: "9", tag_name: "9", extra_args: "" }
          - { base: "oraclelinux", tag: "8", tag_name: "8", extra_args: "" }
          - { base: "oraclelinux", tag: "7", tag_name: "7", extra_args: "" }

          # Photon OS
          - { base: "photonos", tag: "5.0", tag_name: "5", extra_args: "" }
          - { base: "photonos", tag: "4.0", tag_name: "4", extra_args: "" }
          - { base: "photonos", tag: "3.0", tag_name: "3", extra_args: "" }
          - { base: "photonos", tag: "2.0", tag_name: "2", extra_args: "" }
          - { base: "photonos", tag: "1.0", tag_name: "1", extra_args: "" }

          # Rocky Linux
          - { base: "rockylinux", tag: "9", tag_name: "9", extra_args: "" }
          - { base: "rockylinux", tag: "8", tag_name: "8", extra_args: "" }

          # Ubuntu
          - { base: "ubuntu", tag: "24.10",         tag_name: "24.10", extra_args: "" }
          - { base: "ubuntu", tag: "24.04",         tag_name: "24.04", extra_args: "" }
          - { base: "ubuntu", tag: "23.10",         tag_name: "23.10", extra_args: "" }
          - { base: "ubuntu", tag: "23.04",         tag_name: "23.04", extra_args: "" }
          - { base: "ubuntu", tag: "22.10",         tag_name: "22.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "22.04",         tag_name: "22.04", extra_args: "" }
          - { base: "ubuntu", tag: "21.10",         tag_name: "21.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "21.04",         tag_name: "21.04", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "20.10",         tag_name: "20.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "20.04",         tag_name: "20.04", extra_args: "" }
          - { base: "ubuntu", tag: "19.10",         tag_name: "19.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "19.04",         tag_name: "19.04", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "18.10",         tag_name: "18.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "18.04",         tag_name: "18.04", extra_args: "" }
          - { base: "ubuntu", tag: "17.10",         tag_name: "17.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "17.04",         tag_name: "17.04", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "16.10",         tag_name: "16.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "16.04",         tag_name: "16.04", extra_args: "" }
          - { base: "ubuntu", tag: "wily-20160526", tag_name: "15.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "15.04",         tag_name: "15.04", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "14.10",         tag_name: "14.10", extra_args: "OLD_RELEASE=true" }
          - { base: "ubuntu", tag: "14.04",         tag_name: "14.04", extra_args: "" }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ams21/cpkg-docker
            ghcr.io/ams21/cpkg-docker
          flavor: |
            latest=false
            prefix=
            suffix=
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ matrix.cfg.base }}-${{ matrix.cfg.tag_name }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          build-args: |
           TAG=${{ matrix.cfg.tag }}
           ${{ matrix.cfg.extra_args }}
          file: ./${{ matrix.cfg.base }}.dockerfile
          push: true
          platforms: "linux/amd64"
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Attest Docker Hub
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/ams21/cpkg-docker
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Attest GitHub Container Registry
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/ams21/cpkg-docker
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
